name: Benchmark

on:
  push:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: 'true'
        submodules: 'recursive'
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
    - name: Run Tests
      run: cargo bench
